/*
 Navicat Premium Data Transfer

 Source Server         : kamera
 Source Server Type    : PostgreSQL
 Source Server Version : 150001 (150001)
 Source Host           : db.yuakxuiihrtlwwwjrdyb.supabase.co:5432
 Source Catalog        : postgres
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 150001 (150001)
 File Encoding         : 65001

 Date: 14/11/2023 00:30:17
*/


-- ----------------------------
-- Sequence structure for kamera_image_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."kamera_image_id_seq";
CREATE SEQUENCE "public"."kamera_image_id_seq"
    INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for user_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."user_id_seq";
CREATE SEQUENCE "public"."user_id_seq"
    INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Table structure for kamera_image
-- ----------------------------
DROP TABLE IF EXISTS "public"."kamera_image";
CREATE TABLE "public"."kamera_image" (
    "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
     INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
    "type" varchar COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
    "url" text COLLATE "pg_catalog"."default" DEFAULT ''::text,
    "exif" json,
    "rating" int2 DEFAULT '0'::smallint,
    "detail" varchar COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
    "create_time" timestamp(6) DEFAULT now(),
    "update_time" timestamp(6),
    "del" int2 NOT NULL DEFAULT '0'::smallint
);
COMMENT ON COLUMN "public"."kamera_image"."type" IS '图片类型';
COMMENT ON COLUMN "public"."kamera_image"."url" IS '图片地址';
COMMENT ON COLUMN "public"."kamera_image"."exif" IS '图片 exif 信息';
COMMENT ON COLUMN "public"."kamera_image"."rating" IS '图片评分';
COMMENT ON COLUMN "public"."kamera_image"."detail" IS '图片描述';
COMMENT ON COLUMN "public"."kamera_image"."create_time" IS '创建时间';
COMMENT ON COLUMN "public"."kamera_image"."update_time" IS '更新时间';
COMMENT ON COLUMN "public"."kamera_image"."del" IS '逻辑删除：0->可用；1->删除';
COMMENT ON TABLE "public"."kamera_image" IS '图片信息表';

-- ----------------------------
-- Table structure for kamera_user
-- ----------------------------
DROP TABLE IF EXISTS "public"."kamera_user";
CREATE TABLE "public"."kamera_user" (
    "id" int8 NOT NULL DEFAULT nextval('user_id_seq'::regclass),
    "username" varchar(32) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
    "password" varchar(200) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
    "avatar" varchar(200) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
    "role" varchar(32) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
    "email" varchar(64) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
    "name" varchar(20) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
    "telephone" varchar(11) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
    "remark" varchar(255) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
    "create_time" timestamp(6) DEFAULT now(),
    "update_time" timestamp(6),
    "status" int2 NOT NULL DEFAULT 0,
    "del" int2 NOT NULL DEFAULT '0'::smallint
);
COMMENT ON COLUMN "public"."kamera_user"."username" IS '用户名';
COMMENT ON COLUMN "public"."kamera_user"."password" IS '密码';
COMMENT ON COLUMN "public"."kamera_user"."avatar" IS '头像';
COMMENT ON COLUMN "public"."kamera_user"."role" IS '角色';
COMMENT ON COLUMN "public"."kamera_user"."email" IS '邮箱';
COMMENT ON COLUMN "public"."kamera_user"."name" IS '昵称';
COMMENT ON COLUMN "public"."kamera_user"."telephone" IS '手机号';
COMMENT ON COLUMN "public"."kamera_user"."remark" IS '备注';
COMMENT ON COLUMN "public"."kamera_user"."create_time" IS '创建时间';
COMMENT ON COLUMN "public"."kamera_user"."update_time" IS '更新时间';
COMMENT ON COLUMN "public"."kamera_user"."status" IS '启用状态：0->可用；1->禁用';
COMMENT ON COLUMN "public"."kamera_user"."del" IS '逻辑删除：0->可用；1->删除';
COMMENT ON TABLE "public"."kamera_user" IS 'kamera 用户表';

-- ----------------------------
-- Primary Key structure for table kamera_image
-- ----------------------------
ALTER TABLE "public"."kamera_image" ADD CONSTRAINT "kamera_image_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Indexes structure for table kamera_user
-- ----------------------------
CREATE UNIQUE INDEX "idx_user_username" ON "public"."kamera_user" USING btree (
    "username" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table kamera_user
-- ----------------------------
ALTER TABLE "public"."kamera_user" ADD CONSTRAINT "user_pkey" PRIMARY KEY ("id");
